export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  COURSES: "/courses",
  PROJECTS: "/projects",
  STUDENTS: "/students",
  LEADERBOARD: "/leaderboard",
  ACHIEVEMENTS: "/achievements",
  ADMIN: "/admin",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_STUDENTS: "/admin/students",
  ADMIN_LEADERBOARD: "/admin/leaderboard",
  ADMIN_ACHIEVEMENTS: "/admin/achievements",
  NOT_FOUND: "/404",
};
