export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  COURSES: "/courses",
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  PROJECTS: "/projects",
  PROJECT_DETAILS: (id: string) => `/projects/${id}`,
  STUDENTS: "/students",
  LEADERBOARD: "/leaderboard",
  ACHIEVEMENTS: "/achievements",
  ADMIN: "/admin",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_CREATE_COURSE: "/admin/courses/create",
  ADMIN_EDIT_COURSE: (id: string) => `/admin/courses/${id}/edit`,
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_CREATE_CATEGORY: "/admin/categories/create",
  ADMIN_EDIT_CATEGORY: (id: string) => `/admin/categories/${id}/edit`,
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_STUDENTS: "/admin/students",
  ADMIN_LEADERBOARD: "/admin/leaderboard",
  ADMIN_ACHIEVEMENTS: "/admin/achievements",
  NOT_FOUND: "/404",
};
